on: [push]

jobs:
  upload-app:
    runs-on: ubuntu-latest
    name: Upload app of Kobiton
    steps:
      - uses: actions/checkout@v3
      - uses: sonhmle/test-hello-world-composite-action@v2.4
        with:
          kobi_username: ${{ secrets.KOBI_USERNAME }}
          kobi_api_key: ${{ secrets.KOBI_API_KEY }}
          upload_app_id: 275643
          app_name: Android-test
          app_path: ./app-to-upload/android-test.apk
